feed/urls.py
from django.urls import path
from . import views
app_name = "feed"
urlpatterns = [
    path('', views.index, name='index'),
    path('entry/<int:pk>/', views.entry_page, name='entry_page'),
    path('feed/new', views.add_feed, name='add_feed'),
    path('feed/reload', views.reload_all_feeds, name='reload_all_feeds'),
    path('feed/delete', views.delete_subscription, name='delete_subscription'),
    path('feed/entryinteraction/<int:pk>/read', views.change_entry_read_status, name='change_entry_read_status'),
    path('latest/', views.latest, name='latest'),
    path('current/', views.currently_reading, name='currently_reading'),
    path('feed/entryinteraction/<int:pk>/currently_reading', views.mark_as_currently_reading, name='mark_as_currently_reading'),
    path('feed/utils/find_urls_on_page', views.save_urls_from_page, name='save_urls_from_page'),
    path('feed/utils/find_urls_on_page/confirmation', views.save_urls_from_page_confirmation, name='save_urls_from_page_confirmation'),
    path('feed/utils/find_urls_on_page/confirm_urls', views.save_urls_from_page_confirm_urls, name='save_urls_from_page_confirm_urls'),
    path('feed/temp_urls/delete', views.delete_from_temp_urls_session, name='delete_from_temp_urls_session'),
    path('feed/feedlessentry/<int:pk>/delete', views.feedless_entry_deletion, name='feedless_entry_deletion')
]

reader/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('feed.urls')),
	path('indieauth/', include('indieauth.urls')),
    path('registration/', include('registration.urls')),
    path('admin/', admin.site.urls),
]

feed/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
class FeedlessEntry(models.Model):
	url = models.TextField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	def __str__(self):
		return self.url

class SiteFeed(models.Model):
	url = models.TextField()
	title = models.TextField(null=True, blank=True)
	feed_url = models.TextField(null=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	last_modified = models.DateTimeField(auto_now_add=True, blank=True, null=True)
	etag = models.TextField(null=True, blank=True)
	def __str__(self):
		if self.feed_url:

			return self.url + "-" + self.feed_url
		else:
			return self.url
class Entry(models.Model):
	url = models.TextField()
	title = models.TextField()
	content = models.TextField(null=True, blank=True)
	summary = models.TextField(null=True, blank=True)
	published = models.DateTimeField(null=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	story_id = models.TextField(null=True, blank=True)
	feed = models.ForeignKey(SiteFeed, on_delete=models.CASCADE, null=True)
	

	def __str__(self):
		return self.title
# this is how user's will subscribe to a feed, create the site feed on addition
# or subscribe user
class Subscription(models.Model):
	feed = models.ForeignKey(SiteFeed, on_delete=models.CASCADE)
	last_updated = models.DateTimeField(null=True, blank=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	def __str__(self):
		return self.feed.title

class EntryInteraction(models.Model):
	connection = models.ForeignKey(
        Entry, on_delete=models.CASCADE)
	read = models.BooleanField(default=False)
	currently_reading = models.BooleanField(default=False)
	sub = models.ForeignKey(Subscription, on_delete=models.CASCADE)
	def __str__(self):
		return self.connection.title

feed/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Entry, SiteFeed, Subscription, EntryInteraction, FeedlessEntry
import feedparser
import mf2py
import datetime
import requests
import re
import html
import urllib.parse
from django.utils.dateparse import parse_datetime
from django.utils.timezone import utc
from bs4 import BeautifulSoup
from django.core.paginator import Paginator
from django.utils import timezone
from django.utils.html import strip_tags
import bleach
from django.contrib import messages
from .urlsOnPage import urlsOnPage
from .utils import schemeify_url
from django.contrib import messages
from dateutil import parser
from .feedTools import check_feed
from django.contrib.auth.decorators import login_required
max_mins_until_reload_feed = 5

@login_required
def feedless_entry_deletion(request, pk):
	if request.method == "POST":
		if pk:
			get_object_or_404(FeedlessEntry, user=request.user, pk=pk).delete()
	return HttpResponseRedirect(reverse('feed:currently_reading'))
"""
When you load the page, 
see if any of the feeds have been updated 
since that feeds last been checked by the user. 
If it has, get that feed’s newest posts after that 
time and create entries for the user.
"""
@login_required
def delete_from_temp_urls_session(request):
	if request.POST.get("url_to_delete_index", None) != None:
		
		index = int(request.POST["url_to_delete_index"])
		if request.session.get("temp_urls", None) != None:
			request.session["temp_urls"].pop(index)
			request.session.save()
	return HttpResponseRedirect(reverse('feed:save_urls_from_page_confirmation'))
@login_required
def save_urls_from_page_confirm_urls(request):
	if request.method == "POST" and request.session.get("temp_urls", None) != None:
		entries = [FeedlessEntry(url=url, user=request.user) for url in request.session['temp_urls']]
		FeedlessEntry.objects.bulk_create(entries)
		del request.session["temp_urls"]
	return HttpResponseRedirect(reverse('feed:currently_reading'))
@login_required
def save_urls_from_page_confirmation(request):
	return render(request, "feed/urls_on_page_confirmation.html", {'possible_urls': request.session["temp_urls"]})

@login_required
def save_urls_from_page(request):
	if request.method == "POST":
		url = request.POST["urls_from_page"]
		try:
			urls = urlsOnPage(schemeify_url(url))
			if urls == []:
				request.session['temp_urls'] = None
				del request.session["temp_urls"]
				messages.error(request, 'The webpage you submitted has no URLs on it.')
				return HttpResponseRedirect(reverse('feed:currently_reading'))
			request.session['temp_urls'] = urls
		except ValueError:
			request.session['temp_urls'] = None
			del request.session["temp_urls"]
			messages.error(request, 'There was a problem processing that URL. Please enter a valid URL and try again later.')
			return HttpResponseRedirect(reverse('feed:currently_reading'))
		return HttpResponseRedirect(reverse('feed:save_urls_from_page_confirmation'))
@login_required
def check_subs(request):
	subscriptions = Subscription.objects.filter(user=request.user)

	for sub in subscriptions:
		if sub.feed.last_modified != sub.last_updated:
			# add entries
			# set sub last_updated to last_modified
			if not sub.last_updated:
				check_since = datetime.date.min
			else:
				check_since = sub.last_updated

			new_entries = Entry.objects.filter(feed=sub.feed, created_at__gte=check_since)
			for new_entry in new_entries:
				EntryInteraction.objects.get_or_create(connection=new_entry, sub=sub)
				
			sub.last_updated = sub.feed.last_modified
			sub.save()
	return subscriptions
@login_required
def index(request):
	subscriptions = check_subs(request)

	entries = EntryInteraction.objects.filter(currently_reading=False, sub__user=request.user).order_by('-connection__published').select_related('connection')

	paginator = Paginator(entries, 15)

	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)

	return render(request, 'feed/index.html', {"entries": page_obj, "subs": subscriptions})

@login_required
def latest(request):
	subscriptions = check_subs(request)
	date = datetime.datetime.now()
	start_date = date + datetime.timedelta(-date.weekday(), weeks=-1)
	entries = EntryInteraction.objects.filter(currently_reading=False, sub__user=request.user, connection__published__gte=start_date).order_by('-connection__published').select_related('connection')

	paginator = Paginator(entries, 15)

	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)

	return render(request, 'feed/index.html', {"entries": page_obj, "subs": subscriptions, "page_type": "latest"})

@login_required
def currently_reading(request):
	entries = EntryInteraction.objects.filter(currently_reading=True, sub__user=request.user).order_by('-connection__published').select_related('connection')
	feedless_urls = FeedlessEntry.objects.filter(user=request.user)
	paginator = Paginator(entries, 15)

	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	return render(request, 'feed/currently_reading.html', {"entries": page_obj, "feedless_urls": feedless_urls, "page_type": "currently_reading"})

@login_required
def mark_as_currently_reading(request, pk):
	if request.method == 'POST':
		if pk:
			entry_interaction = get_object_or_404(EntryInteraction, sub__user=request.user, pk=pk)
			entry_interaction.currently_reading = not entry_interaction.currently_reading
			entry_interaction.save() 
	return latest_or_index(request.POST.get("page_type", None))

def latest_or_index(page_type):
	print(page_type)
	if page_type == 'latest':
		return HttpResponseRedirect(reverse('feed:latest'))
	elif page_type == 'currently_reading':
		return HttpResponseRedirect(reverse("feed:currently_reading")) 
	else:
		return HttpResponseRedirect(reverse('feed:index')) 

@login_required
def add_feed(request):
	if request.method == 'POST':
		url = request.POST.get("url", None)
		if url:
			try:
				feed = check_feed(url)
				if feed:
					obj = Subscription(feed=feed, user=request.user)
					obj.save()
				else:
					messages.error(request, 'Site did not work.')
			except:
				messages.error(request, "Error with site's feed")
			return latest_or_index(request.POST.get("page_type", None))

	return latest_or_index(request.POST.get("page_type", None))

@login_required
def delete_subscription(request):
	if request.method == 'POST':
		pk = request.POST.get("id", None)
		if pk:
			sub = get_object_or_404(Subscription, user=request.user, pk=pk)
			sub.delete()
	return latest_or_index(request.POST.get("page_type", None))

@login_required
def reload_all_feeds(request):
	if request.method == "POST":
		subscriptions = Subscription.objects.filter(user=request.user)
		for sub in subscriptions:
			if sub.feed.feed_url:
				check_feed(sub.feed.feed_url)
			else:
				check_feed(sub.feed.url)
	return latest_or_index(request.POST.get("page_type", None))

@login_required
def entry_page(request, pk):
	entry = get_object_or_404(Entry, pk=pk)
	return_page_number = request.GET.get('return_page')
	page_type = request.GET.get('page_type')
	return render(request, 'feed/entry.html', {"entry": entry, "return_page": return_page_number, "page_type":page_type})

@login_required
def change_entry_read_status(request, pk):
	if request.method == 'POST':
		if pk:
			entry_interaction = get_object_or_404(EntryInteraction,sub__user=request.user, pk=pk)
			entry_interaction.read = not entry_interaction.read
			entry_interaction.save() 
	return latest_or_index(request.POST.get("page_type", None))

feed/templates/feed/currently_reading.html
{% extends "feed/index.html" %}
{%block title_for_page%}
    Feed - Current
{%endblock%}
{% block non_entry_list %}

<form method="post" action="{%url 'feed:save_urls_from_page' %}">
    {% csrf_token %}
    <label for='add-urls-from-page-input'>Add the main links from a page to this feed:</label>
    <div class="add-url">
        <input id="add-urls-from-page-input" class="add-url__input" name="urls_from_page" type="text">
        <input type="Submit" class="add-url__btn"  value="Submit">
    </div>
</form>

<ul>
    {% for entry in feedless_urls%}
    <li class="container_feedless_post">
            <a href="{{entry.url}}" class="feedless_post">{{entry.url}}</a>
            <form class="feedless_post__form" method="post" action="{%url 'feed:feedless_entry_deletion' entry.pk %}">
                {% csrf_token %}
                <input id="feedless_post--delete__{{entry.pk}}" class="feedless_post--delete" type="submit" value="X">
                <label for="feedless_post--delete__{{entry.pk}}">Delete</label>
            </form>
    </li>
    {%endfor%}
</ul>
{%endblock%}

feed/templates/feed/entry.html
{% extends "base/index.html" %}
{% block title_for_page %}
	Feed - {{entry.title|truncatechars:50}}
{%endblock%}
{% block content %}
<a class="return_to_feed" href="{%if page_type == 'latest'%}{% url 'feed:latest' %}{%else%}{% url 'feed:index' %}{%endif%}?page={{return_page}}">Go back to feed</a>

<section class="entrypiece">
	<h1 class="entrypiece__title">{{entry.title|truncatechars:50}}</h1>
	<h2 class="entrypiece__date">{{entry.published}}</h2>
	<h3 class="entrypiece__origin">Originally from: <a href="{{entry.url}}">{{entry.feed.url}}</a></h3>
	<div class="entrypiece__content">
		{% autoescape off %}
				{{entry.content }}
				{% endautoescape %}
		{%endblock%}
	</div>
</section>

feed/templates/feed/index.html
{% extends "base/index.html" %}
{% block title_for_page %}
    {% if 'latest' in request.path %}
        Feed - Latest
    {% elif 'current' in request.path %}
        Feed - Current
    {%else%}
        Feed - Main
    {%endif%}
{%endblock%}
{% block content %}

<h1>Your Wonderful Reader</h1>
{% if 'latest' in request.path %}
<h2 class="main-title">Latest</h2>
{%elif 'current' in request.path%}
<h2 class="main-title">Current</h2>
{%else%}
<h2 class="main-title">Main</h2>
{%endif%}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li class="error-text possible_message {% if message.tags %} {{ message.tags }} {% endif %}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% block non_entry_list %}
<form action="{% url 'feed:add_feed' %}" method="post">
    {% csrf_token %}
    <label for="new_url_to_add">New URL to add: </label>
    <div class="add-url">
        <input class="add-url__input" placeholder="Eg. https://www.example.org" id="new_url_to_add" type="text" name="url" value="{{ current_name }}">
        {%if page_type%}<input hidden="true" type="text" name="page_type" value="{{page_type}}">{%endif%}
        <button class="add-url__btn" type="submit">Save</button>
    </div>
    </form>
<form class="reload-feeds" action="{% url 'feed:reload_all_feeds' %}" method="post"> 
    {% csrf_token %}
    {%if page_type%}<input hidden="true" type="text" name="page_type" value="{{page_type}}">{%endif%}
    <label>Reload feeds: <input class="reload-feeds__btn"type="submit" value="⟳"/></label>
</form>
<ul class="subs">
    {% for sub in subs%}
    <li class="subscription">
        {{sub.feed.title}} - {{sub.feed.url}}
        <form class="subscription___form" action="{% url 'feed:delete_subscription' %}" method="post"> 
            {% csrf_token %}
            <input type="text" name="id" hidden="true" value="{{sub.id}}">
            {%if page_type%}<input hidden="true" type="text" name="page_type" value="{{page_type}}">{%endif%}
            <input type="submit" class="subscription__delete" value="Delete"/>
        </form>
    </li>
    {%endfor%}
</ul>
{%endblock%}
<section class="all-entries">
    {%for entry_interaction in entries %}
    {% with entry=entry_interaction.connection%}
    <div class="entry">
            <span>
                {% if entry.title == "No title"%}
                <div class="entry__title"><a href="{% url 'feed:entry_page' entry.id %}?return_page={{ entries.number }}{%if page_type%}&page_type={{page_type}}{%endif%}">{{entry.content|truncatechars:75|striptags}}</a></div>
                {%else%}
                <div class="entry__title"><a href="{% url 'feed:entry_page' entry.id %}?return_page={{ entries.number }}{%if page_type%}&page_type={{page_type}}{%endif%}">{{entry.title|truncatechars:75|striptags}}</a></div>
                {%endif%}
                {% if entry.summary%}
                <div class="entry__summary">{{entry.summary|truncatechars:100|striptags}}</div>
                {%endif%}
            </span>
            <span>
                <form class="entry__seen-unseen" method="post" action="{% url 'feed:change_entry_read_status' entry_interaction.pk %}">
                    {% csrf_token %}
                    <input id="entry__seen-unseen__{{entry.pk}}" class="entry__seen-unseen__btn {%if not entry_interaction.read%}entry__seen-unseen__btn--unread{%endif%}"  type="submit" value="⬤"/>
                    <label class="entry__seen-unseen__label" for="entry__seen-unseen__{{entry.pk}}">{%if entry_interaction.read%}Mark as unread{%else%}Mark as read{%endif%}</label>
                    {%if page_type%}<input hidden="true" type="text" name="page_type" value="{{page_type}}">{%endif%}
                </form>
                <form class="entry__currently_reading" method="post" action="{% url 'feed:mark_as_currently_reading' entry_interaction.pk %}">
                    {% csrf_token %}
                    <input type="submit" class="entry__currently_reading__btn" value="{%if entry_interaction.currently_reading%}Move to Main{%else%}Move to Current{%endif%}"/>
                    {%if page_type%}<input hidden="true" type="text" name="page_type" value="{{page_type}}">{%endif%}
                </form>
            </span>
    </div>
    {%endwith%}
    {%endfor%}
</section>
<div class="pagination">
    <span class="step-links">
        {% if entries.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ entries.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ entries.number }} of {{ entries.paginator.num_pages }}.
        </span>

        {% if entries.has_next %}
            <a href="?page={{ entries.next_page_number }}">next</a>
            <a href="?page={{ entries.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{%endblock%}

feed/templates/feed/urls_on_page_confirmation.html
{% extends "base/index.html" %}
{% block title_for_page %}
	Feed - Adding URLs
{%endblock%}
{%block content%}
<h1>URLs to add from page given</h1>
<ul>
    {% for url in possible_urls%}
        <li class="url_confirmation__li"><span class="url_confirmation__possiblities"><a href="{{url}}">{{url}}</a><form class="url_confirmation__possiblities__form" action="{% url 'feed:delete_from_temp_urls_session' %}" method="post">{% csrf_token %}<input type="hidden" name="url_to_delete_index" value="{{ forloop.counter0 }}"><input  class="url_confirmation__delete" type="submit" value="Delete"></form></span></li>
    {%endfor%}
</ul>
<form class="url_confirmation" method="post" action="{% url 'feed:save_urls_from_page_confirm_urls' %}">{% csrf_token %}<input id="url_confirmation__accept" type="submit" value="Add URLs"></form>
{%endblock%}