feed/urls.py
from django.urls import path
from . import views
app_name = "feed"
urlpatterns = [
    path('', views.index, name='index'),
    path('entry/<int:pk>/', views.entry_page, name='entry_page'),
    path('feed/new', views.add_feed, name='add_feed'),
    path('feed/reload', views.reload_all_feeds, name='reload_all_feeds'),
    path('feed/delete', views.delete_subscription, name='delete_subscription'),
    path('feed/entryinteraction/<int:pk>/read', views.change_entry_read_status, name='change_entry_read_status'),
    path('latest/', views.latest, name='latest'),
    path('current/', views.currently_reading, name='currently_reading'),
    path('feed/entryinteraction/<int:pk>/currently_reading', views.mark_as_currently_reading, name='mark_as_currently_reading'),
    path('feed/utils/find_urls_on_page', views.save_urls_from_page, name='save_urls_from_page'),
    path('feed/utils/find_urls_on_page/confirmation', views.save_urls_from_page_confirmation, name='save_urls_from_page_confirmation'),
    path('feed/utils/find_urls_on_page/confirm_urls', views.save_urls_from_page_confirm_urls, name='save_urls_from_page_confirm_urls'),
    path('feed/temp_urls/delete', views.delete_from_temp_urls_session, name='delete_from_temp_urls_session'),
    path('feed/feedlessentry/<int:pk>/delete', views.feedless_entry_deletion, name='feedless_entry_deletion')
]

reader/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('feed.urls')),
	path('indieauth/', include('indieauth.urls')),
    path('registration/', include('registration.urls')),
    path('admin/', admin.site.urls),
]

registration/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'registration'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

base/templates/base/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title_for_page %}Feed{%endblock%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest'%}">
    <link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
</head>
<body class="{%block body_classes%}{%endblock%}">
    <script>0/*Prevent flash of unstyled content*/</script>
{%block nav%}
<nav class="nav">
    <a class="nav__link {%if request.path == '/' %}nav__link--active{%endif%}" href="/">Main</a>
    <a class="nav__link {%if request.path == '/latest/' %}nav__link--active{%endif%}" href="/latest">Latest</a>
    <a class="nav__link {%if request.path == '/current/' %}nav__link--active{%endif%}" href="/current">Current</a>
    {% if user.is_authenticated %}
        <a id="nav__logout" class="nav__link nav__logout" href="{% url 'registration:logout' %}">Logout</a>
    {%endif%}
</nav>
{%endblock%}
<div class="all-content">
{% block content %}

    {% endblock %}
</div>
</body>
</html>